--insert into EMPLOYEE values
--(1,'Baloga','Nagasaki','Female','Karachi'),
--(2,'Mehak','Kamran','Female','Karachi'),
--(3,'Oreo','Herosheema','Male','Karachi'),
--(4,'Teenaga','TOKYO','Male','Karachi'),
--(5,'Ayesha','Kamran','Female','Karachi'),
--(6,'Bilal','Ahmed','Male','Karachi'),
--(7,'Saman','Tauqeer','Female','Karachi')

--INSERT INTO EMPLOYEEDESIGNATION VALUES 
--(1,1500,'MANAGER'),
--(2,50000,'DEPUTY MANAGER'),
--(3,4700,'MANAGER'),
--(4,1500,'SECRETARY'),
--(5,1500,'MANAGER'),
--(6,150000,'FINANCE HEAD'),
--(7,95000,'HEAD')

--SELECT * FROM EMPLOYEE

--SELECT * FROM EMPLOYEEDESIGNATION

--SELECT TOP 5 *FROM EMPLOYEE

--SELECT TOP 5 FIRSTNAME FROM EMPLOYEE

--SELECT DISTINCT LASTNAME FROM EMPLOYEE

--SELECT MAX(SALARY) AS MAXSALARY FROM EMPLOYEEDESIGNATION 

--SELECT AVG(SALARY) AS AVERAGE FROM EMPLOYEEDESIGNATION

--SELECT MIN(SALARY) AS MINIMUM FROM EMPLOYEEDESIGNATION

--SELECT COUNT(FIRSTNAME) FROM EMPLOYEE

--SELECT FIRSTNAME FROM EMPLOYEE WHERE LASTNAME='KAMRAN'

--SELECT FIRSTNAME FROM EMPLOYEE WHERE LASTNAME<> 'KAMRAN'

--SELECT * FROM EMPLOYEEDESIGNATION

--SELECT EMPLOYEEID FROM EMPLOYEEDESIGNATION WHERE SALARY<15000

--SELECT EMPLOYEEID FROM EMPLOYEEDESIGNATION WHERE SALARY<15000 AND POSITION='MANAGER'

--SELECT EMPLOYEEID FROM EMPLOYEEDESIGNATION WHERE SALARY<15000 OR POSITION='HEAD'


--SELECT * FROM EMPLOYEE WHERE LASTNAME IS NOT NULL

--SELECT * FROM EMPLOYEE WHERE LASTNAME LIKE 'N%'

--SELECT EMPLOYEEID FROM EMPLOYEE WHERE FIRSTNAME IN ('BALOGA','MEHAK','AYESHA')
--SELECT EMPLOYEEID FROM EMPLOYEE 
--WHERE FIRSTNAME='BALOGA' OR FIRSTNAME='MEHAK' OR FIRSTNAME='AYESHA'