--SELECT AGE FROM EMPLOYEE FULL OUTER JOIN WAREHOUSEINFO ON EMPLOYEE.FIRSTNAME=WAREHOUSEINFO.FIRSTNAME
--GROUP BY AGE
--HAVING AVG(AGE)<=50
--ORDER BY AGE desc 
--SELECT * FROM EMPLOYEE

--UPDATE EMPLOYEE
--SET LASTNAME ='HAIDER'
--WHERE EMPLOYEEID=8


--UPDATE EMPLOYEE
--SET EMPLOYEEID=9
--WHERE FIRSTNAME = 'AQEEL'AND LASTNAME='AHMED'

--SELECT* FROM EMPLOYEEDESIGNATION

--DELETE FROM EMPLOYEEDESIGNATION
--WHERE SALARY=2000 AND POSITION='PEON'


--UPDATE EMPLOYEE 
--SET FIRSTNAME='ADEEL'
--WHERE EMPLOYEEID=9

--SELECT * FROM EMPLOYEE

--DELETE FROM EMPLOYEE WHERE FIRSTNAME='ADIL' AND LASTNAME='HAIDER'


--select AVG( DESIG.SALARY) AS SAL  from employee AS  EMP join EMPLOYEEDESIGNATION AS DESIG on EMP.EMPLOYEEID=DESIG.EMPLOYEEID
--GROUP BY SALARY 
--HAVING AVG(DESIG.SALARY) <=16000 
--ORDER BY  SALARY DESC

--select * from EMPLOYEEDESIGNATION

select FIRSTNAME  + ' ' +  LASTNAME  AS NAME FROM EMPLOYEE AS EMP LEFT OUTER JOIN EMPLOYEEDESIGNATION AS DESIG ON EMP.EMPLOYEEID=DESIG.EMPLOYEEID

