--SELECT * FROM EMPLOYEE

--SELECT * FROM EMPLOYEE ORDER BY EMPLOYEEID DESC

--SELECT LASTNAME , EMPLOYEEID FROM EMPLOYEE WHERE GENDER ='FEMALE' ORDER BY FIRSTNAME DESC , LASTNAME DESC

SELECT COUNT(GENDER) FROM EMPLOYEE GROUP BY GENDER 